import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import path from "node:path";
import { readFileSync, mkdirSync, copyFileSync, existsSync } from "fs";
import { execSync } from "child_process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isProduction = process.argv.includes('production');
const isWatch = process.argv.includes('--watch');

function loadDotenvIfPresent(dotenvPath = path.join(process.cwd(), '.env')) {
	try {
		const content = readFileSync(dotenvPath, 'utf8');
		for (const rawLine of content.split(/\r?\n/)) {
			const line = rawLine.trim();
			if (!line || line.startsWith('#')) continue;

			const equalsIndex = line.indexOf('=');
			if (equalsIndex === -1) continue;

			const key = line.slice(0, equalsIndex).trim();
			let value = line.slice(equalsIndex + 1).trim();

			if (!key) continue;
			if (process.env[key] !== undefined) continue;

			if (
				(value.startsWith('"') && value.endsWith('"')) ||
				(value.startsWith("'") && value.endsWith("'"))
			) {
				value = value.slice(1, -1);
			}

			process.env[key] = value;
		}
	} catch {
		// ignore
	}
}

function deployToObsidianPluginsDir(outputDir) {
	const pluginsDir = process.env.OBSIDIAN_PLUGINS_DIR;
	if (!pluginsDir) return;

	const manifestRaw = readFileSync('manifest.json', 'utf8');
	const manifest = JSON.parse(manifestRaw);
	const pluginId = manifest?.id;

	if (typeof pluginId !== 'string' || !pluginId) {
		throw new Error("Invalid manifest.json: missing 'id'.");
	}

	const targetDir = path.join(pluginsDir, pluginId);
	mkdirSync(targetDir, { recursive: true });

	copyFileSync(path.join(outputDir, 'main.js'), path.join(targetDir, 'main.js'));
	copyFileSync('manifest.json', path.join(targetDir, 'manifest.json'));
	if (existsSync('styles.css')) {
		copyFileSync('styles.css', path.join(targetDir, 'styles.css'));
	}

	// Optional WASM (if present in outputDir)
	const wasmPath = path.join(outputDir, 'fvad.wasm');
	if (existsSync(wasmPath)) {
		copyFileSync(wasmPath, path.join(targetDir, 'fvad.wasm'));
	}
}

loadDotenvIfPresent();

// Get version from manifest.json
const manifest = JSON.parse(readFileSync('./manifest.json', 'utf8'));
const version = manifest.version;
const outputDir = isProduction ? `build/${version}` : 'dist';

// Create output directory if it doesn't exist
mkdirSync(outputDir, { recursive: true });

const buildOptions = {
	banner: {
		js: banner,
	},
	tsconfig: 'tsconfig.json',
	entryPoints: ['src/main-api.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
	...builtins],
	format: 'cjs',
	target: 'es2020',
	logLevel: "error",
	sourcemap: isProduction ? false : 'inline',
	treeShaking: true,
	minify: isProduction,
	outfile: `${outputDir}/main.js`,
	plugins: [
		{
			name: 'deploy-to-obsidian',
			setup(build) {
				build.onEnd((result) => {
					if (result.errors.length > 0) return;
					deployToObsidianPluginsDir(outputDir);
				});
			}
		}
	]
};

// Always copy manifest/styles next to the build output (for local dev & packaging)
['manifest.json', 'styles.css'].forEach(file => {
	if (existsSync(file)) {
		copyFileSync(file, `${outputDir}/${file}`);
	}
});

if (isWatch) {
	const ctx = await esbuild.context(buildOptions);
	await ctx.watch();
} else {
	await esbuild.build(buildOptions);

	if (isProduction) {
	
	// Copy additional files to build directory
	console.log('Copying additional files...');
	['manifest.json', 'styles.css'].forEach(file => {
		if (existsSync(file)) {
			copyFileSync(file, `${outputDir}/${file}`);
			console.log(`  ✓ ${file}`);
		}
	});
	
// Optionally copy WASM (only when explicitly requested)
// Enable by either: `INCLUDE_WASM=true npm run build` or `node esbuild-api.config.mjs production --with-wasm`
const includeWasm = process.env.INCLUDE_WASM === 'true' || process.argv.includes('--with-wasm');
if (includeWasm) {
    const wasmSrc = 'node_modules/@echogarden/fvad-wasm/fvad.wasm';
    if (existsSync(wasmSrc)) {
        copyFileSync(wasmSrc, `${outputDir}/fvad.wasm`);
        console.log('  ✓ fvad.wasm (included by request)');
    } else {
        console.log('  ! fvad.wasm not found (requested)');
    }
} else {
    console.log('  • fvad.wasm intentionally not included (default)');
}

	// Prepare release artifacts (Community distribution requires only 3 files)
	const releaseDir = `${outputDir}/release`;
	mkdirSync(releaseDir, { recursive: true });
	['main.js', 'manifest.json', 'styles.css'].forEach(file => {
		try {
			copyFileSync(`${outputDir}/${file}`, `${releaseDir}/${file}`);
			console.log(`  ✓ release/${file}`);
		} catch (e) {
			console.warn(`  ! missing ${file} (skipped)`);
		}
	});

	// Optionally create zip (if 'zip' command is available)
	try {
		execSync(`zip -j -q ${outputDir}/ai-transcriber-${version}.zip ${releaseDir}/*`);
		console.log(`  ✓ ai-transcriber-${version}.zip (release)`);
	} catch (_) {
		console.log('  ! zip command not found; release zip skipped');
	}
	
	process.exit(0);
	}
}
