import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync, mkdirSync, copyFileSync, existsSync } from "fs";
import { execSync } from "child_process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// Get version from manifest.json
const manifest = JSON.parse(readFileSync('./manifest.json', 'utf8'));
const version = manifest.version;
const outputDir = `build/${version}`;

// Create output directory if it doesn't exist
mkdirSync(outputDir, { recursive: true });

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main-api.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2020',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: `${outputDir}/main.js`,
});

if (prod) {
	await context.rebuild();
	
	// Copy additional files to build directory
	console.log('Copying additional files...');
	['manifest.json', 'styles.css'].forEach(file => {
		if (existsSync(file)) {
			copyFileSync(file, `${outputDir}/${file}`);
			console.log(`  ✓ ${file}`);
		}
	});
	
// Optionally copy WASM (only when explicitly requested)
// Enable by either: `INCLUDE_WASM=true npm run build` or `node esbuild-api.config.mjs production --with-wasm`
const includeWasm = process.env.INCLUDE_WASM === 'true' || process.argv.includes('--with-wasm');
if (includeWasm) {
    const wasmSrc = 'node_modules/@echogarden/fvad-wasm/fvad.wasm';
    if (existsSync(wasmSrc)) {
        copyFileSync(wasmSrc, `${outputDir}/fvad.wasm`);
        console.log('  ✓ fvad.wasm (included by request)');
    } else {
        console.log('  ! fvad.wasm not found (requested)');
    }
} else {
    console.log('  • fvad.wasm intentionally not included (default)');
}

	// Prepare release artifacts (Community distribution requires only 3 files)
	const releaseDir = `${outputDir}/release`;
	mkdirSync(releaseDir, { recursive: true });
	['main.js', 'manifest.json', 'styles.css'].forEach(file => {
		try {
			copyFileSync(`${outputDir}/${file}`, `${releaseDir}/${file}`);
			console.log(`  ✓ release/${file}`);
		} catch (e) {
			console.warn(`  ! missing ${file} (skipped)`);
		}
	});

	// Optionally create zip (if 'zip' command is available)
	try {
		execSync(`zip -j -q ${outputDir}/ai-transcriber-${version}.zip ${releaseDir}/*`);
		console.log(`  ✓ ai-transcriber-${version}.zip (release)`);
	} catch (_) {
		console.log('  ! zip command not found; release zip skipped');
	}
	
	process.exit(0);
} else {
	await context.watch();
}
